sonar.projectKey=aceest_fitness
sonar.projectName=ACEest Fitness
sonar.host.url=http://localhost:9000
sonar.login=sqa_62279c20c9b590360f3c0ab2fff808437bcd2632

sonar.sources=.
sonar.language=py
sonar.sourceEncoding=UTF-8
