apiVersion: v1
kind: Service
metadata:
  name: aceest-bg-service
spec:
  type: NodePort
  selector:
    app: aceest
    version: blue   # 👈 switch to green later
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30008